// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://psfdgxtebbxtdbuhauae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZmRneHRlYmJ4dGRidWhhdWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxMzEzOTcsImV4cCI6MjA4ODcwNzM5N30.RGt1_dIDpW_CNFpCBYPfgXw3W_ieQIvtVsAukprT7-c";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);